DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS baskets CASCADE;
DROP TABLE IF EXISTS basket_lines;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS order_lines;
DROP TABLE IF EXISTS order_status;
DROP TABLE IF EXISTS users;
